core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls', namespace='posts')),
    path('profiles/', include('profiles.urls', namespace='profile')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path
from .views import (
  post_list_and_create,
  load_post_data_view,
  like_unlike_post,
  post_detail,
  post_detail_data_view,
  delete_post, update_post,
  image_upload_view
  )

app_name = 'posts'

urlpatterns = [
    path('', post_list_and_create, name = 'main-board'),
    path('like_unlike/', like_unlike_post, name='like-unlike'),
    path('upload/',image_upload_view , name = 'image-upload'),
    path('<pk>/', post_detail, name='post-detail'),
    path('<pk>/update/',update_post, name = 'post-update'),
    path('<pk>/delete/',delete_post , name = 'post-delete'),
    
    path('data/<int:num_posts>/', load_post_data_view, name = 'posts-data'),
    path('<pk>/data/', post_detail_data_view, name='post-detail-view'),
]

profiles/urls.py
from django.urls import path
from .views import my_profile_view

app_name = 'profiles'

urlpatterns = [
  path('my/', my_profile_view, name='my-profile'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from profiles.models import Profile
class Post(models.Model):
  title = models.CharField(max_length=200)
  body = models.TextField()
  liked = models.ManyToManyField(User, blank=True)
  author = models.ForeignKey(Profile, on_delete=models.CASCADE)
  updated = models.DateTimeField(auto_now=True)
  created = models.DateTimeField(auto_now_add=True)
  class Meta:
    """Meta definition for Post."""
    ordering = ('-created',)
    verbose_name = 'Post'
    verbose_name_plural = 'Posts'

  def get_photos(self):
    return self.photo_set.all()

  def __str__(self):
    return str(self.title)
  
  @property
  def like_count(self):
    return self.liked.all().count()
  
class Photo(models.Model):
  post = models.ForeignKey(Post, on_delete=models.CASCADE)
  image = models.ImageField(upload_to="photos")
  created = models.DateTimeField(auto_now_add=True)
  
  def __str__(self):
      return f"{self.post.title}-{self.pk}"

profiles/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  bio = models.TextField()
  avatar = models.ImageField(default='avatar.png',upload_to='avatars')
  updated = models.DateTimeField(auto_now=True)
  created = models.DateTimeField(auto_now_add=True)
  class Meta:
    """Meta definition for Profile."""

    verbose_name = 'Profile'
    verbose_name_plural = 'Profiles'

  def __str__(self):
    return f"profile of the user {self.user.username}"

posts/forms.py
from typing import cast
from django import forms
from django.forms import fields
from django.forms.models import ModelFormMetaclass, model_to_dict
from .models import Post

class PostForm(forms.ModelForm):
  title = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
  body = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control','rows':3}))
  class Meta:
    model = Post
    fields = ('title', 'body',)

profiles/forms.py
from django import forms
from .models import Profile

class ProfileForm(forms.ModelForm):
  class Meta:
    model =  Profile
    fields = ("bio","avatar",)

posts/views.py
from json.encoder import JSONEncoder
from django.shortcuts import render
from .models import Post, Photo
from django.http import JsonResponse,HttpResponse
from .forms import PostForm
from profiles.models import Profile
from .utils import action_permission
from django.contrib.auth.decorators import login_required

@login_required
def post_list_and_create(request):
  form = PostForm(request.POST or None)
  #qs = Post.objects.all()
  
  if request.is_ajax():
    if form.is_valid():
      author = Profile.objects.get(user=request.user)
      print(author)
      instance = form.save(commit=False)
      instance.author = author
      instance.save()
      return JsonResponse({
        'title': instance.title,
        'body': instance.body,
        'author': instance.author.user.username,
        'id':instance.id,
      })

    
  context = {
    #'qs' :qs,
    'form':form
  }
  return render(request, 'posts/main.html',context)

@login_required
def post_detail(request,pk):
  obj=Post.objects.get(pk=pk)
  print('post_detail',obj)
  form = PostForm()
  
  context ={
    'obj':obj,
    'form':form,
  }
  
  return render(request, 'posts/detail.html', context)
  
@login_required
def load_post_data_view(request, num_posts):
  if request.is_ajax():
    visible = 3
    upper= num_posts
    lower = upper - visible
    size = Post.objects.all().count()
    
    print('Cantidad de posts',size)
    print('Cantidad de UPPER',upper)

    qs = Post.objects.all()
    
    data = []
    for obj in qs:
      item =  {
        'id' : obj.id,
        'title' : obj.title,
        'body' : obj.body,
        'liked': True if request.user in obj.liked.all() else False,
        'count': obj.like_count,
        'author' : obj.author.user.username
      }
      data.append(item)
    return JsonResponse({'data':data[lower:upper], 'size':size})

@login_required
def post_detail_data_view(request, pk):
  obj= Post.objects.get(pk=pk)
  data = {
    'id': obj.id,
    'title': obj.title,
    'body': obj.body,
    'author': obj.author.user.username,
    'logged_in': request.user.username,
  }
  return JsonResponse({'data':data})

@login_required
def like_unlike_post(request):
  if request.is_ajax():
    pk = request.POST.get('pk')
    print(pk)
    obj = Post.objects.get(pk= pk)
    if request.user in obj.liked.all():
      liked = False
      obj.liked.remove(request.user)
    else:
      liked = True
      obj.liked.add(request.user)
    return JsonResponse({'liked': liked, 'count': obj.like_count})

@action_permission
@login_required
def update_post(request, pk):
  obj = Post.objects.get(pk=pk)
  if request.is_ajax():
    new_title = request.POST.get('title')
    new_body = request.POST.get('body')
    obj.title = new_title
    obj.body = new_body
    obj.save()
    return JsonResponse({
      'title':new_title,
      'body': new_body,
    })

@login_required
@action_permission
def delete_post(request,pk):
  obj = Post.objects.get(pk=pk)
  if request.is_ajax():
    obj.delete()
    return JsonResponse({'msg':'some message'})
  return JsonResponse({'msg':'acceso denegado - debe de ingresar por ajax '})
  
@login_required
@action_permission
def image_upload_view(request):
  if request.method == 'POST':
    img = request.FILES.get('file')
    new_post_id = request.POST.get('new_post_id')
    post_id = Post.objects.get(pk = new_post_id)
    Photo.objects.  create(post=post_id, image=img)
    
    print("ID de post",post_id)
    print("new post id", new_post_id)
  return HttpResponse()

profiles/views.py
from django.shortcuts import render
from .models import Profile
from .forms import ProfileForm
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required

@login_required
def my_profile_view(request):
  obj = Profile.objects.get(user=request.user)
  form = ProfileForm(request.POST or None, request.FILES or None, instance=obj)
  if request.is_ajax():
    if form.is_valid():
      instance = form.save()
      return JsonResponse({
        'bio': instance.bio,
        'avatar': instance.avatar.url,
        'user': instance.user.username
      })
  context = {
    'obj':obj,
    'form':form,
  }
  
  return render(request, 'profiles/main.html', context)

posts/templates/posts/detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block scripts %}
  <script src="{% static 'posts/detail.js' %}" defer></script>
{% endblock scripts %}


{% block title %} {{obj.title}} detail {% endblock title %}


{% block content %}
<!-- Modal update -->
<div class="modal fade" id="updateModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Update Posts</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div id="alert-box"></div>
        <form id="update-form">
          {% csrf_token %}
          {{form.as_p}}
          <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-bs-dismiss="modal">close</button>
            <button type="submit" class="btn btn-success">update</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- Delete Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Update Posts</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Estas seguro de eliminar el Post <b>"{{obj.title}}"</b>?
        <div class="modal-footer">
          <form id="delete-form">
            {% csrf_token %}
            <div class="modal-footer">
              <button type="button" class="btn btn-danger" data-bs-dismiss="modal">close</button>
              <button type="submit" class="btn btn-success">delete</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- carousel -->

{% if obj.get_photos %}
  <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      
      {% for p in obj.get_photos %}
        <div class="carousel-item {% if forloop.counter == 1%} active{% endif %}">
          <img src="{{p.image.url}}" class="d-block w-100" alt="photo {{obj.pk}}">
        </div>
      {% endfor %}
        
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
{% else %}
    <div class="mt-2 mb-2">No se tiene imagenes</div>
{% endif %}
  



  <a href="{% url 'posts:main-board'%}" id="back-btn" class="btn btn-info">Back</a>
  <button id="update-btn" class="btn btn-primary not-visible" data-bs-toggle="modal" data-bs-target="#updateModal">Update</button>
  <button id="delete-btn" class="btn btn-danger not-visible" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>
  <div id="spinner-box" class="text-center">
    <div class="spinner-box" role="status"></div>
  </div>
  <div class="mt-1" id="post-box"></div>
{% endblock content %}
  

posts/templates/posts/main.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block scripts %}
  <script src="{% static 'posts/main.js' %}" defer></script>
{% endblock scripts %}


{% block title %}
  posts
{% endblock title %}
  

{% block content %}


<!-- Modal -->
<div class="modal fade" id="addPostModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Create Posts</h5>
        <button type="button" class="btn-close add-modal-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form id="post-form">
          {% csrf_token %}
          {{form.as_p}}
          <div class="modal-footer">
            <button type="button" class="btn btn-danger add-modal-close" data-bs-dismiss="modal">close</button>
            <button type="submit" id="add-btn" class="btn btn-success">+ add</button>
          </div>
        </form>
        <form action="upload/" id ="my-dropzone" class="dropzone dz not-visible" >
          {% csrf_token %}
          <div class="fallback">
            <input name="file" type="file" multiple />
          </div>
        </form>
      </div>

    </div>
  </div>
</div>


<h1>lista de posts</h1>

<div id="alert-box"></div>
<!-- Button trigger modal -->
<button type="button" class="btn btn-info mb-2" data-bs-toggle="modal" data-bs-target="#addPostModal">
  Add Posts
</button>


<div id="posts-box" ></div>
<div id="spinner-border" class="text-center">
  <div class="spinner-border" role="status">
</div>
</div>
<div class="text-center mb-3" id="end-box">
  <button  class="btn btn-primary" id="load-btn">Load more</button>
</div>
    
{% endblock content %}
  

profiles/templates/profiles/main.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block scripts %}
  <script src="{% static 'js/main.js' %}" defer></script>
{% endblock scripts %}


{% block title %}
  Mi profiles
{% endblock title %}


{% block content %}
  <div id="alert-box"></div>
  <h3> {{obj.user}}</h3>
  <hr>
  <div class="text-center" id="avatar-box">
  <img src="{{obj.avatar.url}}" class="rounded"  height="200px" width="auto" alt="{{obj.user.username}}">
  </div>
  <form action="" id="profile-form">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-primary mt-3">Save</button>
  </form>
{% endblock content %}
  
  

templates/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="es">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- favicon -->
    <link rel="icon" href="{% static 'image/logo.ico' %}" type="image/x-icon">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Custom css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    <!-- Dropzone  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.9.3/dropzone.css" integrity="sha512-7uSoC3grlnRktCWoO4LjHMjotq8gf9XDFQerPuaph+cqR7JC9XKGdvN+UwZMC14aAaBDItdRj3DcSDs4kMWUgg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.9.3/dropzone.js" integrity="sha512-9e9rr82F9BPzG81+6UrwWLFj8ZLf59jnuIA/tIf8dEGoQVu7l5qvr02G/BiAabsFOYrIUTMslVN+iDYuszftVQ==" crossorigin="anonymous" referrerpolicy="no-referrer" defer></script>

    <script src="{% static 'js/functions.js' %}" defer></script>
    {% block scripts %}
    {% endblock scripts %}
      
    <title> read posts | {% block title %} {% endblock title %}</title>
  </head>
  <body>
    <div class="container mt-3">
      {% block content %}
      {% endblock content %}
    </div>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

  </body>
</html>